# Generated by Django 4.2.6 on 2023-10-14 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'admin_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('mobile_no', models.BigIntegerField(unique=True)),
                ('vehicle_no', models.CharField(unique=True)),
                ('pancard_no', models.CharField(max_length=10, unique=True)),
                ('bank_name', models.CharField(choices=[('BOB', 'BankOfBaroda'), ('SBI', 'StateBankOfIndia'), ('HDFC', 'HDFC'), ('AXIS', 'AXIS')], max_length=50)),
                ('bankaccount_no', models.CharField(max_length=16)),
                ('IFSC_code', models.CharField(max_length=11)),
            ],
            options={
                'db_table': 'partner_table',
                'managed': False,
            },
        ),
    ]
