# Generated by Django 4.2.6 on 2023-10-14 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_delete_orders'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurant',
            options={},
        ),
    ]
