# Generated by Django 4.2.6 on 2023-10-14 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_restaurant_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='email',
            field=models.CharField(default='klankipalle@hotmail.com', max_length=100),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='password',
            field=models.CharField(default='12345', max_length=100),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='username',
            field=models.CharField(default='Luffy', max_length=100),
        ),
    ]
