# Generated by Django 4.2.5 on 2023-11-04 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_restaurant_email_restaurant_password_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurant',
            options={'managed': False},
        ),
    ]
