# Generated by Django 4.2.5 on 2023-11-04 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_alter_restaurant_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='password',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='username',
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
