# Generated by Django 4.2.5 on 2023-11-04 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_remove_restaurant_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='email',
            field=models.CharField(default='klankipalle@hotmail.com', max_length=100),
        ),
    ]
